### ISSUE TITLE
Probable wrong variable check in VitamFieldsHelper

### ISSUE THREAD

**Issue by fredericBregier** [ProgrammeVitam/vitam#120] opened 2021-11-19 09:56 UTC
https://github.com/ProgrammeVitam/vitam/blob/0f98e57746c79c5a225a5b9526b8109973c84ee1/sources/common/common-database-vitam/common-database-public/src/main/java/fr/gouv/vitam/common/database/builder/query/VitamFieldsHelper.java#L379

Should it be: `hashVersion` instead computed just before?

**Comment by TDevillechabrolle** [comment] 2021-11-19 11:05
You are right Frédéric.
The issue is forwaded to development team
Thierry

**Comment by GiooDev** [comment] 2022-01-19 09:37
Thanks for your feedback.

It will be fixed on the next release of Vitam.

**Closed as completed by GiooDev** 2022-01-19 09:37 UTC
